// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Tr1M9I8knUTvaxM5K9Gzy7fOfGc1zbA',
    appId: '1:139272232990:web:b96e2e0baeca391d36ce0f',
    messagingSenderId: '139272232990',
    projectId: 'evently-app-e600b',
    authDomain: 'evently-app-e600b.firebaseapp.com',
    storageBucket: 'evently-app-e600b.firebasestorage.app',
    measurementId: 'G-NYY7789ZZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Mt3nUTmJg1iDOWV4B8rXwxfu0KbpRKI',
    appId: '1:139272232990:android:fd15234de372e32736ce0f',
    messagingSenderId: '139272232990',
    projectId: 'evently-app-e600b',
    storageBucket: 'evently-app-e600b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXnCk3VuV5gr5DDTU8hWlfbciffPJatjk',
    appId: '1:139272232990:ios:e804f22489aa063736ce0f',
    messagingSenderId: '139272232990',
    projectId: 'evently-app-e600b',
    storageBucket: 'evently-app-e600b.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXnCk3VuV5gr5DDTU8hWlfbciffPJatjk',
    appId: '1:139272232990:ios:e804f22489aa063736ce0f',
    messagingSenderId: '139272232990',
    projectId: 'evently-app-e600b',
    storageBucket: 'evently-app-e600b.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2Tr1M9I8knUTvaxM5K9Gzy7fOfGc1zbA',
    appId: '1:139272232990:web:efd9143d77a5ebbf36ce0f',
    messagingSenderId: '139272232990',
    projectId: 'evently-app-e600b',
    authDomain: 'evently-app-e600b.firebaseapp.com',
    storageBucket: 'evently-app-e600b.firebasestorage.app',
    measurementId: 'G-63RPE139L3',
  );
}
